config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'locations', to: 'users/registrations#new_location'
    post 'locations', to: 'users/registrations#create_location'
  end
  
  root "items#index"
  namespace :items do
    resources :searches, only: :index
  end
  resources :items do
    member do
      get :confirm
      post   '/like/:item_id' => 'likes#like',   as: 'like'
      delete '/like/:item_id' => 'likes#unlike', as: 'unlike'
    end
    collection do
      get :category_children
      get :category_grandchildren
    end
    resources :comments, only: :create
    resources :images, only: [:index,:create]
  end
  resources :users, only: [:show] do
    member do
      get :profile_edit
      post :profile_update
      get :location_edit
      post :location_update
      get :onsale
      get :done
      get :bought
      get :like
    end
    resources :profile, only: [:index]
    resources :creditcards, only: :index
    resources :location, only: :index
  end
  resources :creditcards, only: [:new, :show] do
    collection do
      post 'show', to: 'creditcards#show'
      post 'pay', to: 'creditcards#pay'
      post 'delete', to: 'creditcards#delete'
    end
  end
  resources :purchases, only: [:index] do
    member do
      get 'index', to: 'purchases#index'
      get 'pay', to: 'purchases#pay'
      get 'done', to: 'purchases#done'
    end
  end
  resources :categories, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :user_family_name, :user_first_name, :user_family_name_kana, :user_first_name_kana,:birth, presence: true
  validates :email, uniqueness: true, format: { with: /\A([a-zA-Z0-9])+([a-zA-Z0-9\._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9\._-]+)+\z/ }
  validates :user_family_name, :user_first_name, :user_family_name_kana, :user_first_name_kana, format: { with: /\A[ぁ-んァ-ヶー一-龠]+\z/ }
  validates :password, confirmation: true


  has_many :items, dependent: :destroy
  has_many :comments
  has_one :profile
  has_many :creditcards
  has_one :location
  has_many :likes, dependent: :destroy
  has_many :like_items, through: :likes, source: :item
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  
  private
  def authorization
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted? #ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
    else #ユーザー情報が未登録なので、新規登録画面へ遷移する
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  # GET /resource/sign_up
  def new
    @user = User.new
  end
  
  # POST /resource@
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"]= params[:user][:password]
    @location = @user.build_location
    render :new_location
  end

  def create_location
    @user = User.new(session["devise.regist_data"]["user"])
    @location = Location.new(location_params)
    unless @location.valid?
      flash.now[:alert] = @location.errors.full_messages
      render :new_location and return
    end 
    @user.build_location(@location.attributes)
    if @user.save
      sign_in(:user, @user)
    else
      flash.now[:error] = 'ユーザー情報の保存に失敗しました'
      render :create
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute,:user_family_name,:user_first_name,:user_family_name_kana,:user_first_name_kana,:birth])
  end

  def location_params
    params.require(:location).permit(:family_name,:first_name,:family_name_kana,:first_name_kana,:postal_code, :prefecture,:city,:building_name,:phone_name)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # 
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_profile, only: [:profile_edit, :profile_update]
  before_action :set_location, only: [:location_edit, :location_update]
  before_action :set_header, only: [:show, :onsale, :done, :bought, :like, :location_edit, :profile_edit]
  before_action :set_item, only: [:onsale, :done, :bought, :like]




  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def onsale
  end

  def done
  end

  def bought
  end

  def like
  end

  def location_edit
  end

  def location_update
    @location.update(location_params)
    redirect_to user_path
  end

  def profile_edit
  end

  def profile_update
    @user.update(user_params)
    redirect_to user_path
  end


  private
  def set_profile
    @user = User.find(params[:id])
  end

  def set_location
    @location = current_user.location
  end

  def set_header
    @items = Item.includes(:images).order(:item_purchaser_id, "id DESC")
    @category = Category.all.order("ancestry ASC").limit(13)
    @parents = Category.where(ancestry:nil)
  end

  def user_params
    params.require(:user).permit(:user_family_name, :user_first_name, :user_family_name_kana, :user_first_name_kana, :birth, :introduction, :user_image)
  end

  def location_params
    params.require(:location).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :postal_code, :prefecture, :city, :building_name, :phone_name)
  end

  def set_item
    @items = Item.includes(:user)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/bought.html.haml
.body
  = render partial:"shared/index_header"
  .nav
    %ul.nav__itemscope
      %li.nav__itemscope__itemtype
        = link_to root_path,class: "navgation" do
          FURIMA
        .nav__itemscope__itemtype__right
          　>　
      %li.nav__itemscope__itemtype2
        購入商品一覧
  .main
    = render partial:"shared/user_left_nav"
    .main__right
      .main__right__bought-title 
        購入商品一覧
      .main__right__tabTodo
        .tabContent
          .tabContent__info
            - @items.each do |item|
              - item.images.first(1).each do |image|  
                - if user_signed_in? && current_user.id && item.item_purchaser_id.present? && current_user.id == item.item_purchaser_id
                  = link_to item_path(item.id) do
                    .tabContent__lists
                      .tabContent__lists__img
                        = image_tag "#{image.image}", alt: "テスト", size: "100x70"
                        .items-box_photo__sold
                          .items-box_photo__sold__inner
                            SOLD
                      .tabContent__lists__product-name
                        = item.item_name
                        .bought-sign
                          購入済
                        .like-counts
                          - if item.likes_count.blank?
                            = 0
                          -else
                            = item.likes_count 

  = render partial:"shared/index_footer"
  

app/views/users/done.html.haml
.body
  = render partial:"shared/index_header"
  .nav
    %ul.nav__itemscope
      %li.nav__itemscope__itemtype
        = link_to root_path,class: "navgation" do
          FURIMA
        .nav__itemscope__itemtype__right
          　>　
      %li.nav__itemscope__itemtype2
        出品した商品-売却済み
  .main
    = render partial:"shared/user_left_nav"
    .main__right
      .main__right__title 
        出品した商品
      .main__right__tabTodo
        .tabTodo
          = link_to "出品中", onsale_user_path(current_user.id), class: 'done-onsale'
          = link_to "売却済み", "", class: 'done-sold'

        .tabContent
          .tabContent__info
            - @items.each do |item|
              - item.images.first(1).each do |image|  
                - if user_signed_in? && current_user.id && item.item_purchaser_id.present? && current_user.id == item.user_id 
                  = link_to item_path(item.id) do
                    .tabContent__lists
                      .tabContent__lists__img
                        = image_tag "#{image.image}", alt: "テスト", size: "100x70"
                        .items-box_photo__sold
                          .items-box_photo__sold__inner
                            SOLD
                      .tabContent__lists__product-name
                        = item.item_name
                        .sold-sign
                          売却済
                        .like-counts
                          - if item.likes_count.blank?
                            = 0
                          -else
                            = item.likes_count 

  = render partial:"shared/index_footer"
  

app/views/users/like.html.haml
.body
  = render partial:"shared/index_header"
  .nav
    %ul.nav__itemscope
      %li.nav__itemscope__itemtype
        = link_to root_path,class: "navgation" do
          FURIMA
        .nav__itemscope__itemtype__right
          　>　
      %li.nav__itemscope__itemtype2
        お気に入り商品一覧
  .main
    = render partial:"shared/user_left_nav"
    .main__right
      .main__right__bought-title 
        お気に入り商品一覧
      .main__right__tabTodo
        .tabContent
          .tabContent__info
            - current_user.like_items.each do |item|
              = link_to item_path(item.id) do
                .tabContent__lists
                  .tabContent__lists__img
                    = image_tag asset_path(item.images[0].image), :size =>'100x70'
                  .tabContent__lists__product-name
                    = item.item_name           
                    .like-sign
                      お気に入り済
                    .like-counts
                      - if item.likes_count.blank?
                        = 0
                      -else
                        = item.likes_count                        

  = render partial:"shared/index_footer"
  

app/views/users/location_edit.html.haml
.body
  = render partial:"shared/index_header"
  .nav
    %ul.nav__itemscope
      %li.nav__itemscope__itemtype
        = link_to root_path,class: "navgation" do
          FURIMA
        .nav__itemscope__itemtype__right
          　>　
      %li.nav__itemscope__itemtype2
        発送元・お届け先住所変更
  .main
    = render partial:"shared/user_left_nav"
    .main__right
      .main__right__top
        発送元・お届け先住所変更
      .main__right__form
        = form_with(model: @location, url: location_update_user_path, method: :post, local:true) do |f|
          = render "devise/shared/error_messages", resource: @location
          .form-group-edit2
            .form-group-edit2__label
              .form-group-edit2__label__moji
                苗字
              %span.form-group-edit2__label__require 必須
            = f.text_field :family_name, {class:'form-group-edit2__input'}
          .form-group-edit2
            .form-group-edit2__label
              .form-group-edit2__label__moji
                名前
              %span.form-group-edit2__label__require 必須
            = f.text_field :first_name, {class:'form-group-edit2__input'}
          .form-group-edit2
            .form-group-edit2__label
              .form-group-edit2__label__moji
                苗字 (カナ)
              %span.form-group-edit2__label__require 必須
            = f.text_field :family_name_kana, {class:'form-group-edit2__input'}
          .form-group-edit2
            .form-group-edit2__label
              .form-group-edit2__label__moji
                名前（カナ）
              %span.form-group-edit2__label__require 必須
            = f.text_field :first_name_kana, {class:'form-group-edit2__input'}
          .form-group-edit2
            .form-group-edit2__label
              .form-group-edit2__label__moji
                郵便番号
              %span.form-group-edit2__label__require 必須
            = f.text_field :postal_code, {class:'form-group-edit2__input'}
          .form-group-edit2
            .form-group-edit2__label
              .form-group-edit2__label__moji
                都道府県
              %span.form-group-edit2__label__require 必須
            = f.text_field :prefecture, {class:'form-group-edit2__input'}
          .form-group-edit2
            .form-group-edit2__label
              .form-group-edit2__label__moji
                市町村
              %span.form-group-edit2__label__require 必須
            = f.text_field :city, {class:'form-group-edit2__input'}
          .form-group-edit2
            .form-group-edit2__label
              .form-group-edit2__label__moji
                建物名
            = f.text_field :building_name, {class:'form-group-edit2__input'}
          .form-group-edit2
            .form-group-edit2__label
              .form-group-edit2__label__moji
                電話番号
              %span.form-group-edit2__label__require 必須
            = f.text_field :phone_name, {class:'form-group-edit2__input'}
          .form_submit
            = f.submit '変更する', class: "edit-btn-default-btn"

= render partial: "shared/index_footer"

app/views/users/onsale.html.haml
.body
  = render partial:"shared/index_header"
  .nav
    %ul.nav__itemscope
      %li.nav__itemscope__itemtype
        = link_to root_path,class: "navgation" do
          FURIMA
        .nav__itemscope__itemtype__right
          　>　
      %li.nav__itemscope__itemtype2
        出品した商品-出品中
  .main
    = render partial:"shared/user_left_nav"
    .main__right
      .main__right__title 
        出品した商品
      .main__right__tabTodo
        .tabTodo
          = link_to "出品中", "", class: 'onsale'
          = link_to "売却済み", done_user_path(current_user.id), class: 'sold'


        .tabContent
          .tabContent__info
            - @items.each do |item|
              - item.images.first(1).each do |image|  
                - if user_signed_in? && current_user.id && item.item_purchaser_id.blank? && current_user.id == item.user_id 
                  = link_to item_path(item.id) do
                    .tabContent__lists
                      .tabContent__lists__img
                        = image_tag "#{image.image}", alt: "テスト", size: "100x70"
                      .tabContent__lists__product-name
                        = item.item_name
                        .onsale-sign
                          出品中
                        .like-counts
                          - if item.likes_count.blank?
                            = 0
                          -else
                            = item.likes_count  

  = render partial:"shared/index_footer"
  

app/views/users/profile_edit.html.haml
.body
  = render partial:"shared/index_header"
  .nav
    %ul.nav__itemscope
      %li.nav__itemscope__itemtype
        = link_to root_path,class: "navgation" do
          FURIMA
        .nav__itemscope__itemtype__right
          　>　
      %li.nav__itemscope__itemtype2
        本人情報の変更
  .main
    = render partial:"shared/user_left_nav"
    .main__right
      .main__right__top
        本人情報の登録・変更
      .main__right__form
        = form_with(url: profile_update_user_path,model: @user, method: :post, local:true) do |f|
          -# = render "devise/shared/error_messages", resource: @location
          .form-group-edit
            苗字
            = f.text_field :user_family_name, {class:'form-group-edit__input'}
          .form-group-edit
            名前
            = f.text_field :user_first_name, {class:'form-group-edit__input'}
          .form-group-edit
            苗字（カナ）
            = f.text_field :user_family_name_kana, {class:'form-group-edit__input'}
          .form-group-edit
            名前（カナ） 
            = f.text_field :user_first_name_kana, {class:'form-group-edit__input'}
          .form-group-edit
            誕生日
            = f.text_field :birth, {class:'form-group-edit__input'}
          .form_submit
            = f.submit '変更する', class: "edit-btn-default-btn"

  .appbanner
    .appbanner__inner
      %h1.inner__title
        だれでもかんたん、人生を変えるフリマアプリ
      %p.inner__text
        今すぐ無料ダウンロード！
      .inner__btn
        = link_to "#" do
          = image_tag "/material/badge/Download_on_the_App_Store_Badge.svg", class: "abtn"
        = link_to "#" do
          = image_tag "/material/badge/google-play-badge.png", class: "gbtn"
  .footer
    %ul.footer__contents
      %li.content
        %h1.title
          FURIMAについて
        %ul.lists
          %li.list
            = link_to "#", class: "list" do
              会社概要（運営会社）
          %li.list
            = link_to "#", class: "list" do
              プライバシーポリシー
          %li.list
            = link_to "#", class: "list" do
              FURIMA利用規約
          %li.list
            = link_to "#", class: "list" do
              ポイントに関する特約
      %li.content
        %h1.title
          FURIMAを見る
        %ul.lists
          %li.list
            = link_to "#", class: "list" do
              カテゴリー一覧
          %li.list
            = link_to "#", class: "list" do
              ブランド一覧
      %li.content
        %h1.title
          ヘルプ＆ガイド
        %ul.lists
          %li.list
            = link_to "#", class: "list" do
              FURIMAガイド
          %li.list
            = link_to "#", class: "list" do
              FURIMAロゴ利用ガイドライン
          %li.list
            = link_to "#", class: "list" do
              お知らせ
    .footer__logo
      =link_to "#" do
        = image_tag "/material/logo/logo-white.png", width: "160px", height: "46px"
    %p.logo__under
      ©︎　FURIMA

  = link_to new_item_path do
    .exhibit
      .text
        出品する
      = image_tag  "/material/icon/icon_camera.png", class: "exhibit__icon"

app/views/users/show.html.haml
.body
  = render partial:"shared/index_header"
  .nav
    %ul.nav__itemscope
      %li.nav__itemscope__itemtype
        = link_to root_path,class: "navgation" do
          FURIMA
        .nav__itemscope__itemtype__right
          　>　
      %li.nav__itemscope__itemtype2
        マイページ
  .main
    = render partial:"shared/user_left_nav"
    .main__right
      .main__right__head
        プロフィール
      .main__right__userIcon
        .button
          .button__top
          .button__name
            = current_user.nickname
          .button__number
            .button__number__box

      
      .main__right__profile
        .main__right__profile__box
          .main__right__profile__box__list1
            .main__right__profile__box__list1__label
              苗字
            .main__right__profile__box__list1__content
              = @user.user_family_name
          .main__right__profile__box__list
            .main__right__profile__box__list__label
              名前
            .main__right__profile__box__list__content
              = @user.user_first_name
          .main__right__profile__box__list
            .main__right__profile__box__list__label
              苗字（かな）
            .main__right__profile__box__list__content
              = @user.user_family_name_kana
          .main__right__profile__box__list
            .main__right__profile__box__list__label
              名前（かな）
            .main__right__profile__box__list__content
              = @user.user_first_name_kana
          .main__right__profile__box__list
            .main__right__profile__box__list__label
              誕生日
            .main__right__profile__box__list__content
              = @user.birth
  = render partial: "shared/index_footer"