config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'locations', to: 'users/registrations#new_location'
    post 'locations', to: 'users/registrations#create_location'
  end
  
  root "items#index"
  namespace :items do
    resources :searches, only: :index
  end
  resources :items do
    member do
      get :confirm
      post   '/like/:item_id' => 'likes#like',   as: 'like'
      delete '/like/:item_id' => 'likes#unlike', as: 'unlike'
    end
    collection do
      get :category_children
      get :category_grandchildren
    end
    resources :comments, only: :create
    resources :images, only: [:index,:create]
  end
  resources :users, only: [:show] do
    member do
      get :profile_edit
      post :profile_update
      get :location_edit
      post :location_update
      get :onsale
      get :done
      get :bought
      get :like
    end
    resources :profile, only: [:index]
    resources :creditcards, only: :index
    resources :location, only: :index
  end
  resources :creditcards, only: [:new, :show] do
    collection do
      post 'show', to: 'creditcards#show'
      post 'pay', to: 'creditcards#pay'
      post 'delete', to: 'creditcards#delete'
    end
  end
  resources :purchases, only: [:index] do
    member do
      get 'index', to: 'purchases#index'
      get 'pay', to: 'purchases#pay'
      get 'done', to: 'purchases#done'
    end
  end
  resources :categories, only: [:show]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :content, presence: true
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :item
  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :comments
  has_many :images, dependent: :destroy
  belongs_to :user
  belongs_to :category, dependent: :destroy, optional: true
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  def self.search(search)
    return Item.all unless search
    Item.where('item_name LIKE(?)', "%#{search}%")
  end



  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

# allow_destroy: trueで、親(item)が削除されると紐づいているimage,category
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :all_blank
  validates                     :images , presence: { message: "がありません" }

# 商品名、商品詳細、商品状態、配送料、配送元、配送日時、商品化価格のバリデーション
  validates :item_name, :description, :price, presence: true
  validates :category_id, presence: { message: "を選択してください" }
  validates :condition, presence: { message: "を選択してください" }
  validates :shipping_fee_payer, presence: { message: "を選択してください" } 
  validates :prefecture_id, presence: { message: "を選択してください" }
  validates :shipping_days, presence: { message: "を選択してください" }


  # 商品名40文字以内
  validates :item_name, length: {minimum: 1,maximum: 40}
  # 商品詳細1000文字以内
  validates :description, length: {minimum: 1,maximum: 1000}

  # 商品価格のバリデーション
  validates :price, presence: true, numericality: { only_integer: true,greater_than: 300, less_than: 9999999}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :item, counter_cache: :likes_count
  belongs_to :user
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user, optional: true
  validates :family_name, :first_name, :family_name_kana, :first_name_kana, :postal_code, :prefecture, :city, :phone_name, presence: true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :user_family_name, :user_first_name, :user_family_name_kana, :user_first_name_kana,:birth, presence: true
  validates :email, uniqueness: true, format: { with: /\A([a-zA-Z0-9])+([a-zA-Z0-9\._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9\._-]+)+\z/ }
  validates :user_family_name, :user_first_name, :user_family_name_kana, :user_first_name_kana, format: { with: /\A[ぁ-んァ-ヶー一-龠]+\z/ }
  validates :password, confirmation: true


  has_many :items, dependent: :destroy
  has_many :comments
  has_one :profile
  has_many :creditcards
  has_one :location
  has_many :likes, dependent: :destroy
  has_many :like_items, through: :likes, source: :item
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    user
  end
end

app/helpers/brand_helper.rb
module BrandHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul.error-message-box
      - resource.errors.full_messages.each do |message|
        %li.error-message
          = message

app/views/shared/_footer.html.haml
.container__footer
  = image_tag("logo.png",width:"134",height:"36")

app/views/shared/_index_footer.html.haml
.appbanner
  .appbanner__inner
    %h1.inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.inner__text
      今すぐ無料ダウンロード！
    .inner__btn
      = link_to "https://www.apple.com/jp/ios/app-store" do
        = image_tag "/material/badge/Download_on_the_App_Store_Badge.svg", class: "abtn"
      = link_to "https://play.google.com/store?hl=ja" do
        = image_tag "/material/badge/google-play-badge.png", class: "gbtn"

.footer
  %ul.footer__contents
    %li.content
      %h1.title
        FURIMAについて
      %ul.lists
        %li.list
          = link_to "#", class: "list" do
            会社概要（運営会社）
        %li.list
          = link_to "#", class: "list" do
            プライバシーポリシー
        %li.list
          = link_to "#", class: "list" do
            FURIMA利用規約
        %li.list
          = link_to "#", class: "list" do
            ポイントに関する特約
    %li.content
      %h1.title
        FURIMAを見る
      %ul.lists
        %li.list
          = link_to "#", class: "list" do
            カテゴリー一覧
        %li.list
          = link_to "#", class: "list" do
            ブランド一覧
    %li.content
      %h1.title
        ヘルプ＆ガイド
      %ul.lists
        %li.list
          = link_to "#", class: "list" do
            FURIMAガイド
        %li.list
          = link_to "#", class: "list" do
            FURIMAロゴ利用ガイドライン
        %li.list
          = link_to "#", class: "list" do
            お知らせ
  = link_to root_path do
    = image_tag "/material/logo/logo-white.png", size: "160x46", class: "footer__logo"

  %p
    © FURIMA
  
  = link_to new_item_path do
    .exhibit
      .text
        出品する
      = image_tag "/material/icon/icon_camera.png", class: "exhibit__icon"

app/views/shared/_index_header.html.haml
.header
  .header__box
    .header__box__main
      = link_to root_path do
        = image_tag "/material/logo/logo.png", size: "140x40"
      = form_with(url: items_searches_path, local: true, method: :get, class: "search__box") do |form|
        = form.text_field :keyword, placeholder: "キーワードから探す", class: "search__box__form"
        = form.submit "検索", class: "search__box__btn"
    .header__box__sub
      %ul.category-brand
        %li.category
          = image_tag "/material/icon/icon_category.png", size: "15x15"
          = link_to "カテゴリー", root_path
          %ul.firstmenu-parent
            - @parents.each do |parent|
              %li.parent-name
                = link_to category_path(parent.id),class: "categories__name" do
                  = parent.name
                %ul.secondmenu-children
                  - parent.children.each do |child|
                    %li.children-name
                      = link_to category_path(child.id),class: "categories__name" do
                        = child.name
                      %ul.thirdmenu-grandchildren
                        - child.children.each do |grandchild|
                          %li.grandchildren-name
                            = link_to category_path(grandchild.id),class: "categories__name" do
                              = grandchild.name

        %li.brand
          = image_tag "/material/icon/icon_brand.png", size: "15x15"
          = link_to "ブランド一覧",root_path
          %ul.abnc
            - @items.first(6).each do |item|
              %li.brand__lists
                = link_to category_path(item.category_id),class: "brands__name" do
                  = item.brand_name

      - if user_signed_in?
        %ul.lists__right
          %li
            = link_to "マイページ",user_path(current_user.id), class: 'logins'
      - else
        %ul.lists__right
          %li
            = link_to "ログイン",new_user_session_path, class: 'logins'
          %li
            = link_to "新規登録",new_user_registration_path, class: 'signin'
          %li.facebook
            = icon('fab', 'facebook-f')
            = link_to 'Facebookで登録', user_facebook_omniauth_authorize_path, method: :post 
          -# %li
          -#   = link_to 'Googleで登録', user_google_oauth2_omniauth_authorize_path, method: :post

app/views/shared/_items_new_footer.html.haml
.lower-content
  .legal-info-box
    .hoge
      = link_to "#" do
        .privacy-policy-box プライバシーポリシー
      = link_to "#" do  
        .terms-box FURIMA利用規約
      = link_to "#" do
        .specified-commercial-transaction-act-box 特定商取引に関する表記
  .footer__logo
    .logo-img
      = image_tag "/logo-white.png", size: "160x46"
    .logo-text ©FURIMA

app/views/shared/_like.html.haml
.option__like{:id => "like-link-#{@item.id}"}
  - if current_user.likes.find_by(item_id: item.id)
    = link_to unlike_item_path(@item.id, @item.id), method: :delete, remote: true, class: "option__like-on" do
      .fas.fa-heart
      .option__like-on__text いいね！
      .option__like-on__count
        =item.likes.count
  - else
    = link_to  like_item_path(@item.id, @item.id), method: :post, remote: true, class: "option__like-off" do
      .fas.fa-heart
      .option__like-off__text いいね！
      .option__like-off__count
        =item.likes.count

app/views/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "ログイン", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  .enter-registration
    アカウントをお持ちでない方はこちら
  .enter-registration__contents
    = link_to new_registration_path(resource_name),class: 'enter-registration__contents__content' do
      .enter-registration__contents__content--btn
        %h2 新規登録
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    -# = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/shared/_user_left_nav.html.haml
.main__left
  .main__left__nav
    .nav__lists
      %li.nav__lists__list
        =link_to user_path(current_user.id), class: "moji" do
          マイページ
      %li.nav__lists__list
        =link_to onsale_user_path(current_user.id),class: "moji" do
          出品した商品-出品中
      %li.nav__lists__list
        =link_to done_user_path(current_user.id),class: "moji" do
          出品した商品-売却済み
      %li.nav__lists__list
        =link_to bought_user_path(current_user.id),class: "moji" do
          購入商品一覧
      %li.nav__lists__list
        =link_to like_user_path(current_user.id),class: "moji" do
          お気に入り商品一覧
      %li.nav__lists__list
        =link_to location_edit_user_path,class: "moji" do
          発送元・お届け先住所変更
      %li.nav__lists__list
        =link_to pay_creditcards_path,class: "moji" do
          支払い方法
      %li.nav__lists__list
        =link_to profile_edit_user_path,class: "moji" do
          本人情報の変更
      %li.nav__lists__list
        = link_to "ログアウト",destroy_user_session_path,method: :delete, class: 'moji'