config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'locations', to: 'users/registrations#new_location'
    post 'locations', to: 'users/registrations#create_location'
  end
  
  root "items#index"
  namespace :items do
    resources :searches, only: :index
  end
  resources :items do
    member do
      get :confirm
      post   '/like/:item_id' => 'likes#like',   as: 'like'
      delete '/like/:item_id' => 'likes#unlike', as: 'unlike'
    end
    collection do
      get :category_children
      get :category_grandchildren
    end
    resources :comments, only: :create
    resources :images, only: [:index,:create]
  end
  resources :users, only: [:show] do
    member do
      get :profile_edit
      post :profile_update
      get :location_edit
      post :location_update
      get :onsale
      get :done
      get :bought
      get :like
    end
    resources :profile, only: [:index]
    resources :creditcards, only: :index
    resources :location, only: :index
  end
  resources :creditcards, only: [:new, :show] do
    collection do
      post 'show', to: 'creditcards#show'
      post 'pay', to: 'creditcards#pay'
      post 'delete', to: 'creditcards#delete'
    end
  end
  resources :purchases, only: [:index] do
    member do
      get 'index', to: 'purchases#index'
      get 'pay', to: 'purchases#pay'
      get 'done', to: 'purchases#done'
    end
  end
  resources :categories, only: [:show]
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :comments
  has_many :images, dependent: :destroy
  belongs_to :user
  belongs_to :category, dependent: :destroy, optional: true
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  def self.search(search)
    return Item.all unless search
    Item.where('item_name LIKE(?)', "%#{search}%")
  end



  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

# allow_destroy: trueで、親(item)が削除されると紐づいているimage,category
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :all_blank
  validates                     :images , presence: { message: "がありません" }

# 商品名、商品詳細、商品状態、配送料、配送元、配送日時、商品化価格のバリデーション
  validates :item_name, :description, :price, presence: true
  validates :category_id, presence: { message: "を選択してください" }
  validates :condition, presence: { message: "を選択してください" }
  validates :shipping_fee_payer, presence: { message: "を選択してください" } 
  validates :prefecture_id, presence: { message: "を選択してください" }
  validates :shipping_days, presence: { message: "を選択してください" }


  # 商品名40文字以内
  validates :item_name, length: {minimum: 1,maximum: 40}
  # 商品詳細1000文字以内
  validates :description, length: {minimum: 1,maximum: 1000}

  # 商品価格のバリデーション
  validates :price, presence: true, numericality: { only_integer: true,greater_than: 300, less_than: 9999999}
end

app/controllers/items/searches_controller.rb
class Items::SearchesController < ApplicationController
  def index
    @items = Item.search(params[:keyword])
    @page = @items.page(params[:page]).per(20)
    @category = Category.all.order("ancestry ASC").limit(13)
    @parents = Category.where(ancestry:nil)
    @q = Item.ransack(params[:q])
    @items_ransack = @q.result(distinct: true)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:confirm, :show, :edit, :update]
  before_action :set_category, only: [:index, :new, :create, :show, :edit]
  before_action :set_category_parent, only: [:index, :show]
  before_action :set_items_image, only: [:index, :show]



  def index
  end

  def new
    @item = Item.new
    @item.images.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      @item.images.build
      render :new
    end
  end

  def confirm
    @location = current_user.location
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user).order("id DESC")
  end

  def category_children
    @category_children = Category.find(params[:productcategory]).children
  end

  # Ajax通信で送られてきたデータをparamsで受け取り､childrenで子を取得
  def category_grandchildren
    @category_grandchildren = Category.find(params[:productcategory]).children
  end

  def search
    respond_to do |format|
      format.html
      format.json do
        @children = Category.find(params[:parent_id]).children
      end
    end
  end

  def edit
    @selected_grandchild_category = @item.category
    @selected_child_category = @selected_grandchild_category.parent
    @selected_parent_category = @selected_child_category.parent
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    redirect_to user_path(current_user.id) and return unless item.destroy
    redirect_to onsale_user_path(current_user.id)
  end

  def search
    @items = Item.search(params[:keyword])
  end


  private
  def item_params
    params.require(:item).permit(:item_name, :description, :category_id, :brand_name, :size, :condition,
                                  :shipping_fee_payer,:prefecture_id, :shipping_days, :price,
                                  images_attributes: [:image, :_destroy, :id], categories_attributes: [:name]).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.includes(:user).find(params[:id])
  end

  def user_params
    params.require(:item).permit(user:[:nickname])
  end

  def set_category
    @category = Category.all.order("ancestry ASC").limit(13)
  end

  def set_category_parent
    @parents = Category.where(ancestry:nil)
  end

  def set_items_image
    @items = Item.includes(:images).order(:item_purchaser_id, "id DESC")
  end

end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items/searches_helper.rb
module Items::SearchesHelper
end

app/views/items/_footer.html.haml
.appbanner
  .appbanner__inner
    %h1.inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.inner__text
      今すぐ無料ダウンロード！
    .inner__btn
      = link_to "#" do
        = image_tag "/material/badge/Download_on_the_App_Store_Badge.svg", class: "abtn"
      = link_to "#" do
        = image_tag "/material/badge/google-play-badge.png", class: "gbtn"

.footer
  %ul.footer__contents
    %li.content
      %h1.title
        FURIMAについて
      %ul.lists
        %li.list
          = link_to "#", class: "list" do
            会社概要（運営会社）
        %li.list
          = link_to "#", class: "list" do
            プライバシーポリシー
        %li.list
          = link_to "#", class: "list" do
            FURIMA利用規約
        %li.list
          = link_to "#", class: "list" do
            ポイントに関する特約
    %li.content
      %h1.title
        FURIMAを見る
      %ul.lists
        %li.list
          = link_to "#", class: "list" do
            カテゴリー一覧
        %li.list
          = link_to "#", class: "list" do
            ブランド一覧
    %li.content
      %h1.title
        ヘルプ＆ガイド
      %ul.lists
        %li.list
          = link_to "#", class: "list" do
            FURIMAガイド
        %li.list
          = link_to "#", class: "list" do
            FURIMAロゴ利用ガイドライン
        %li.list
          = link_to "#", class: "list" do
            お知らせ
  = link_to root_path do
    = image_tag "/material/logo/logo-white.png", size: "160x46", class: "footer__logo"

  %p
    © FURIMA

  = link_to new_item_path do
    .exhibit
      .text
        出品する
      = image_tag "/material/icon/icon_camera.png", class: "exhibit__icon"

app/views/items/_header.html.haml
.header
  .header__box
    .header__box__main
      = link_to root_path do
        = image_tag "/material/logo/logo.png", size: "140x40"
      = form_with url: "#", class: "search__box" do |f|
        = f.text_field :content, class: 'search__box__form', placeholder: ' キーワードから探す'
      = link_to "#" do
        = image_tag "/material/icon/icon-search 1.png", size: "24x24", class: "search__box__btn"
    .header__box__sub
      %ul.lists__left
        %li
          = link_to "#",class: "category" do
            カテゴリー
        %li
          = link_to "#",class: "brand" do
            ブランド

      - if user_signed_in?
        %ul.lists__right
          %li
            = link_to "ログアウト",destroy_user_session_path,method: :delete, class: 'logins'
          %li
            = link_to "マイページ",user_path(current_user.id), class: 'logins'
      - else
        %ul.lists__right
          %li
            = link_to "ログイン",new_user_session_path, class: 'logins'
          %li
            = link_to "新規登録",new_user_registration_path, class: 'signin'

app/views/items/confirm.html.haml
.body-confirm
  .items-confirm-header
    =link_to root_path do
      = image_tag "/logo.png", size: "185x49"
  .main-confirm-contents
    = form_with url:"#" do |f|
      .main-confirm-content
        .main-confirm-content__header
          %h2 購入内容の確認
        .main-confirm-content__buy-item
          = image_tag "#{@item.images.first.image}", alt: "テスト", size: "100x100"
          .main-confirm-content__buy-item__group
            .main-confirm-content__buy-item__group__item-name
              %h3 
              = @item.item_name
            .main-confirm-content__buy-item__group__item-price
              %h3
                ¥
                = @item.price
            .main-confirm-content__buy-item__group__shipping-fee-payer
              %h3 （税込）送料込み
        .main-confirm-content__payment
          .main-confirm-content__payment__group
            .main-confirm-content__payment__group__price-point
              .main-confirm-content__payment__group__price-point__price
                %h2 支払い金額
                %h2
                  ¥
                  = @item.price
            .main-confirm-content__payment__group__way
              %h2 支払い方法
              = link_to user_path(current_user.id) do
                %h3 マイページより登録してください
            .main-confirm-content__payment__group__location
              %h2 配送先
              %h3
                〒
                = @location.postal_code
                %br/
                = @location.prefecture
                = @location.city
                = @location.building_name
                %br/
                = current_user.nickname
            .main-confirm-content__payment__group__submit
              = link_to "購入する", purchase_path(@item.id), method: :get, class: "confirm-submit"
              = link_to "もどる", :back, class: "return-btn"
          
  = render partial:"shared/items_new_footer"

app/views/items/edit.html.haml
.body-edit
  .items-new-header
    =link_to root_path do
      = image_tag "/logo.png", size: "185x49"
      
  = render 'layouts/error_messages', model: @item

  .edit-main-content
    = form_with model: @item,local: true do |f|
      .edit-main-content__box
        .edit-title
          .edit-title__size
            %h2 編集
        .edit-main-content__box__image-content
          .edit-main-content__box__image-content__field
            .edit-main-content__box__image-content__field__subtitle
              .index 商品画像
              .caution 必須
            %p.memo 
              最大
              /
              10
              /
              枚までアップロードできます

            .exmain-box
              .exmain-box__main
                .exmain-box__main__uploader#box-hidden
                  %label.exmain-box__main__uploader__label<>
                    .js-file_group{data: {index: "#{@item.images.count}"}}
                      %i.fa.fa-camera
                      = f.file_field :image, name: "item[images_attributes][#{@item.images.count}][image]", id: "item_photos_attributes_#{@item.images.count}_image", class: 'js-file'

                    .image-upload-description-box
                      %p.first-line ドラッグアンドドロップ
                      %p.second-line またはクリックしてファイルをアップロード

                .exmain-box__main__previews
                  - if @item.persisted?
                    - @item.images.each_with_index do |image, i|
                      .exmain-box__main__previews__view{data: {index: "#{i}"}}
                        .exmain-box__main__previews__view__image
                          = image_tag image.image.url, data: { index: i }, class: 'input_images', width: "112", height: '80'
                          .js-remove.exmain-box__main__previews__view__delete
                            削除
                    = f.fields_for :images, @item.images do |image|
                      - if @item.persisted?
                        = image.check_box :_destroy, include_hidden: false, data:{ index: image.index },class: 'hidden-destroy'
                

                    
        .edit-main-content__box__item-info-content
          .edit-main-content__box__item-info-content__subtitle
            .index 商品名
            .caution 必須
          .item-info-form
            = f.text_field :item_name, placeholder: "40文字まで", class: "name-input-box", size: 40

          .edit-main-content__box__item-info-content__description
            .index 商品の説明
            .caution 必須
          .item-descriptaion-form
            = f.text_area :description, placeholder: "商品の説明(必須 1,000文字以内)(色、素材、重さ、低下、注意点など)例)2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。", class: "description-input-box",rows:"25", cols:"40"
            
        .edit-main-content__box__item-detail-content
          .edit-main-content__box__item-detail-content__field 
            .edit-main-content__box__item-detail-content__field__subtitle 商品詳細

            .category-box
              .index カテゴリー
              .caution 必須
            .selected_category
              = @selected_parent_category.name
              ＞
              = @selected_child_category.name
              ＞
              = @selected_grandchild_category.name
            .warning
              %h4 ※変更する場合は、選び直してください
            .item_category-select
              = f.collection_select :category, @category, :id, :name, { prompt: "選択してください" }, { class: "category_select-box", id: "category_select" }
              %i.fa.fa-chevron-down
            .item_select-children

            .brand-box
              .index ブランド
              .caution 任意
            .brand-form-field
              = f.text_field :brand_name, placeholder:"例）シャネル", class:"brand-input-box"


            .size-box
              .index サイズ
              .caution 任意
            .size-form-field
              = f.text_field :size, placeholder:"サイズを入力してください", class:"size-input-box"

            .condition-box
              .index 商品の状態
              .caution 必須
            .condetion-form-field
              = f.select :condition,
              {新品、未使用:"新品、未使用",
              未使用に近い:"未使用に近い",
              目立った傷や汚れなし:"目立った傷や汚れなし",
              やや傷や汚れあり:"やや傷や汚れあり",
              傷や汚れあり:"傷や汚れあり",
              全体的に状態が悪い:"全体的に状態が悪い"},
              { include_blank: "選択してください"}

        .edit-main-content__box__delivery-info-content
          .edit-main-content__box__delivery-info-content__field 
            .edit-main-content__box__delivery-info-content__field__subtitle-box
              .edit-main-content__box__delivery-info-content__field__subtitle 配送について
              = link_to "#", class:"faq-icon" do
                = icon('fas', 'question-circle', class: 'faq-btn')

            .shipping-fee-payer-box
              .index 配送料の負担
              .caution 必須
            .shipping-fee-payer-form-field
              = f.select :shipping_fee_payer,
              {送料込み（出品者負担）:"送料込み（出品者負担）",
              着払い（購入者負担）:"着払い（購入者負担）"},
              { include_blank: "選択してください"}
            .shipping-location-box
              .index 配送元の地域
              .caution 必須
            .shipping-location-form-field
              = f.collection_select :prefecture_id, Prefecture.all, :id, :name

            .shipping-fee-payer-box
              .index 発送までの日数
              .caution 必須
            .shipping-days-form-field
              = f.select :shipping_days,
              {１〜２日で発送:"１〜２日で発送",
              ２〜３日で発送:"２〜３日で発送",
              ４〜７日で発送:"４〜７日で発送"},
              { include_blank: "選択してください"}
      
        .edit-main-content__box__cost-info-content
          .edit-main-content__box__cost-info-content__subtitle-box
            .edit-main-content__box__cost-info-content__subtitle-box__subtitle 販売価格 (¥300〜¥9,999,999)
            = link_to "#", class:"faq-icon" do
              = icon('fas', 'question-circle', class: 'faq-btn')
            
          .price-info-box
            .price-info-box__left
              .index 販売価格
              .hoge
                .caution 必須
            .price-info-box__right
              %span.currency ¥
              = f.number_field :price, placeholder:"0", class:"price-input-box", min: 300, max:9999999
          
          .sales-commission-info
            .sales-commission-tax 販売手数料（10%）
            .sales-commission-calc
            
          .sales-profit-info
            .sales-profit-subtitle 販売利益
            .sales-profit-calc

          = f.submit "再出品する", class: "sell-btn"

          = link_to :back do
            %input.edit-return-btn{type: "button", value: "もどる"}

          .terms-info-box
            %p.tems-info-description 
              禁止されている行為および出品物を必ずご確認ください。
              /
              偽ブランドや盗品物などの販売は犯罪であり、法律により処罰される可能性があります。
              /
              また、出品をもちまして加盟店規約に同意したことになります。

  = render partial:"shared/index_footer"

app/views/items/index.html.haml
= render partial: "shared/index_header"


.main
  .main__visual
    .main__visual__picture
    .content
      .content__subtitle
        人生を変えるフリマアプリ
      .content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .content__btn
        = link_to "https://www.apple.com/jp/ios/app-store" do
          = image_tag "/material/badge/Download_on_the_App_Store_Badge.svg", class: "abtn"
        = link_to "https://play.google.com/store?hl=ja" do
          = image_tag "/material/badge/google-play-badge.png", class: "gbtn"


  .top__introduction
    .subtitle
      FURIMAが選ばれる3つの理由
      .subtitle__after
    %ul.lists
      %li.list
        .list__pictuer
          = image_tag "/material/pict/pict-reason-01.jpg", size: "300x300"
          .nummber
            1
        %h1.list__title
          %span
            3分 
          ですぐに出品
        %p.list__text
          スマホで入力するだけで簡単に出品できる！

      %li.list
        .list__pictuer
          = image_tag "/material/pict/pict-reason-02.jpg", size: "300x300"
          .nummber
            2
        %h1.list__title
          %span
            シンプル
          で使いやすい
        %p.list__text
          めんどくさい入力は必要なく、検索も購入もスムーズ！

      %li.list
        .list__pictuer
          = image_tag "/material/pict/pict-reason-03.jpg", size: "300x300"
          .nummber
            3
        %h1.list__title
          手数料
          %span
            業界最安
        %p.list__text
          最大3%でお得に出品&購入！


  .top__middle__dl
    .top__middle__dl__picture
    .top__middle__dl__content
      .content__subtitle
        会員数日本一位
      .content__text
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .content__btn
        = link_to "https://www.apple.com/jp/ios/app-store" do
          = image_tag "/material/badge/Download_on_the_App_Store_Badge.svg", class: "abtn"
        = link_to "https://play.google.com/store?hl=ja" do
          = image_tag "/material/badge/google-play-badge.png", class: "gbtn"

  .top__key__features
    .head
      FURIMAの特徴
      .head__after
    .items
      .item
        = image_tag "/material/icon/icon-01.png", size: "216x332", class: "item__img"
        %h3.item__subtitle
          簡単に売り買いできる
        %p.item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .item
        = image_tag "/material/icon/icon-03.png", size: "216x332", class: "item__img"
        %h3.item__subtitle
          売上金は即日振込みに対応
        %p.item__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      .item
        = image_tag "/material/icon/icon-04.png", size: "216x332", class: "item__img"
        %h3.item__subtitle
          様々な支払いに対応
        %p.item__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  .pickup__container
    .pickup__container__category
      .head
        ピックアップカテゴリー
      .product
        .product__title
          新規投稿商品
        .product__lists

          - @items.first(8).each do |item|
            - item.images.first(1).each do |image|
              .product__list
                - if item.item_purchaser_id.blank?
                  = link_to item_path(item.id) do
                    .product__list__img
                      = image_tag "#{image.image}", alt: "テスト", size: "220x150"
                    
                    .product__list__text
                      .item__name
                        = item.item_name
                      .item__details
                        %ul
                          %li.flex-two
                            .category-yen
                              = item.price
                          %li.like-counts
                            - if item.likes_count.blank?
                              = 0
                            -else
                              = item.likes_count
                        %p
                          (税込)



= render partial: "shared/index_footer"

app/views/items/search.html.haml
= form_with(url: search_items_path, local: true, method: :get, class: "search__box") do |form|
  = form.text_field :keyword, placeholder: "キーワードから探す", class: "search__box__form"
  = form.submit "検索", class: "search__box__btn"
.contents.row
  - @items.each do |item|
    = render partial: "item", locals: { item: item }

app/views/items/show.html.haml
%link{:href => "https://unpkg.com/swiper/css/swiper.min.css", :rel => "stylesheet"}/
%script{:src => "https://unpkg.com/swiper/js/swiper.min.js"}

.product
  = render partial:"shared/index_header"

  .product-contents
    .product-contents__inner
      .product-contents__inner__mainbox
        .product-contents__inner__mainbox__top
          .product-contents__inner__mainbox__top__name
            = @item.item_name
          - if 1 < 3
            .product-contents__inner__mainbox__top__itemManage

        .product-contents__inner__mainbox__main-upper-box
          .product-contents__inner__mainbox__main-upper-box__main-image
            .swiper-container.gallery-top
              .swiper-wrapper
                - @item.images.each do |image|
                  - if @item.item_purchaser_id.present?
                    .swiper-slide
                      = image_tag "#{image.image}", alt: "テスト", size: "400x389"
                      .items-box_photo__sold
                        .items-box_photo__sold__inner
                          SOLD
                  - else
                    .swiper-slide
                      = image_tag "#{image.image}", alt: "テスト", size: "400x389"
              / Add Arrows
              .swiper-button-next.swiper-button-white
              .swiper-button-prev.swiper-button-white
              .swiper-pagination
            .swiper-container.gallery-thumbs
              .swiper-wrapper
                - @item.images.each do |image|
                  .swiper-slide
                    = image_tag "#{image.image}", alt: "テスト", size: "100x100"

          .product-contents__inner__mainbox__main-upper-box__table
            .product-contents__inner__mainbox__main-upper-box__table__box
              .leftbox
                出品者
              .rightbox
                = @item.user.nickname
            .product-contents__inner__mainbox__main-upper-box__table__category-box
              .category-leftbox
                カテゴリー
              .category-rightbox
                = link_to category_path(@item.category.parent.parent.id),class:"parent-name" do
                  = @item.category.parent.parent.name

                = link_to category_path(@item.category.parent.id), class:"children-name" do
                  = @item.category.parent.name
                = link_to category_path(@item.category.id), class:"grand-children-name" do
                  = @item.category.name
                
            .product-contents__inner__mainbox__main-upper-box__table__box
              .leftbox
                ブランド
              .rightbox
                = @item.brand_name
            .product-contents__inner__mainbox__main-upper-box__table__box
              .leftbox
                商品のサイズ
              .rightbox
                = @item.size
            .product-contents__inner__mainbox__main-upper-box__table__box
              .leftbox
                商品の状態
              .rightbox
                = @item.condition
            .product-contents__inner__mainbox__main-upper-box__table__box
              .leftbox
                配送料の負担
              .rightbox
                = @item.shipping_fee_payer
            .product-contents__inner__mainbox__main-upper-box__table__box
              .leftbox
                発送元の地域
              .rightbox
                = @item.prefecture.name
            .product-contents__inner__mainbox__main-upper-box__table__box
              .leftbox
                発送日の目安
              .rightbox
                = @item.shipping_days


        .product-contents__inner__mainbox__other-images
          .product-contents__inner__mainbox__other-images__three-images
            .product-contents__inner__mainbox__other-images__three-images__first
            .product-contents__inner__mainbox__other-images__three-images__second
            .product-contents__inner__mainbox__other-images__three-images__thrid
        .product-contents__inner__mainbox__price
          = @item.price
        .product-contents__inner__mainbox__additional-price
          (税込) 送料込み
        - if user_signed_in? && current_user.id == @item.user_id
          .item-buy-btn
            これはあなたの出品物です
        - elsif @item.item_purchaser_id.present?
          .item-sold-notice
            この商品は売却済です
        - else
          = link_to confirm_item_path(@item.id),class: "item-buy-btn" do
            購入画面に進む
        .product-contents__inner__mainbox__description
          = simple_format @item.description

        - if user_signed_in?
          .product-contents__inner__mainbox__links
            .product-contents__inner__mainbox__links__favorite
              = render partial: 'shared/like', locals: { item: @item }
                              
            .product-contents__inner__mainbox__links__report
              .product-contents__inner__mainbox__links__report__icon
                = icon('fa', 'flag',class: 'flag-icon')
              .product-contents__inner__mainbox__links__report__letter
                不適切な商品の通報


      - if user_signed_in? && current_user.id == @item.user_id
        .product-contents__inner__edit-delete-btn-content
          .edit-btn
            = link_to edit_item_path(@item.id), class: "itemManage__edit" do
              .edit-btn__text
                商品の編集
            .selection
              or
            = link_to item_path(@item.id),method: :delete do
              .delete-btn
                この商品を削除する
                

      - if user_signed_in? && current_user
        .product-contents__inner__commentbox
          .product-contents__inner__commentbox__warning
            相手のことを考え丁寧なコメントを心がけましょう.
            %br/
            不快な言葉遣いなどは利用制限や退会処分となることがあります。
          .product-contents__inner__commentbox__content
            = form_with(model: [@item, @comment], local: true) do |form|
              = form.text_area :content, placeholder: "コメントする", class: "product-contents__inner__commentbox__comment"
              .testclass
                = form.submit "SEND", class: "product-contents__inner__commentbox__comment__btn"
          .comments
            %h4 ＜コメント一覧＞
            .comments__box
              - if @comments
                - @comments.each do |comment|
                  .upper-comment
                    .upper-comment__user-name
                      = link_to comment.user.nickname, class: "link"
                    .upper-comment__date
                      = comment.created_at.to_s(:datetime_jp)
                  .lower-comment
                    - if comment.content.present?
                      .lower-comment__content
                        = comment.content
                    - else 
                      %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※


  = render partial:"shared/index_footer"
  

:javascript
  var galleryThumbs = new Swiper('.gallery-thumbs', {
    spaceBetween: 10,
    slidesPerView: 4,
    loop: false,
    freeMode: true,
    loopedSlides: 5, //looped slides should be the same
    watchSlidesVisibility: true,
    watchSlidesProgress: true,
  });
  var galleryTop = new Swiper('.gallery-top', {
    spaceBetween: 10,
    loop: false,
    loopedSlides: 5, //looped slides should be the same
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
    thumbs: {
      swiper: galleryThumbs,
    },
    pagination: {
    el: '.swiper-pagination',
    type: 'bullets',
    clickable: true,
    },
  });

app/views/items/update.html.haml
.update-body
  = render partial:"shared/index_header"
  
  .success
    .success__message
      更新が完了しました。
    = link_to "/",class: "success__btn" do
      投稿一覧へ戻る


  = render partial:"shared/index_footer"   
  